import type { Metadata } from "next";
import localFont from 'next/font/local'

import "./globals.css";
import { Header } from "@/components";
import { ClickerProvider } from "@/lib/ClickerContext";

const fortniteFont = localFont({ src: '../public/Fortnite.ttf' })

export const metadata: Metadata = {
  title: "Fortnite clicker",
  description: "Generated by create next app",
  icons: {
    icon: "/images/vbucks.webp"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fortniteFont.className}>
        <ClickerProvider>
          <Header />
          {children}
        </ClickerProvider>
      </body>
    </html>
  );
}
